# Generated by Django 2.0 on 2020-04-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwors',
            new_name='password',
        ),
    ]
