# Generated by Django 2.0 on 2020-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200418_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=1000)),
                ('actors', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('timelong', models.CharField(max_length=1000)),
                ('IMDb', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DoubanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('taskname', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
