# Generated by Django 2.0 on 2020-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_doubansubject_doubantask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubansubject',
            name='text',
            field=models.TextField(),
        ),
    ]
