# Generated by Django 2.0 on 2020-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20200422_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubantask',
            name='subject',
        ),
        migrations.AddField(
            model_name='doubansubject',
            name='runtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doubansubject',
            name='taskname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doubansubject',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doubantask',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doubantask',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
