# Generated by Django 2.0 on 2020-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20200425_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubansubject',
            name='taskname',
        ),
        migrations.RemoveField(
            model_name='doubansubject',
            name='username',
        ),
        migrations.AddField(
            model_name='doubansubject',
            name='taskid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doubantask',
            name='key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
