# Generated by Django 2.0 on 2020-04-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20200425_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubantask',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
